steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/$REPO_NAME:latest
      - --cache=true
      - --dockerfile=Dockerfile
    id: build
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy
    args:
      - run
      - deploy
      - $REPO_NAME-$_APP_ENV
      - --image
      - gcr.io/$PROJECT_ID/$REPO_NAME:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
timeout: 1500s
