
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '.']
      timeout: 500s
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        - 'run'
        - 'deploy'
        - '$REPO_NAME'
        - '--image'
        - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
        - '--region'
        - 'europe-west1'
        - '--platform'
        - 'managed'
        - '--allow-unauthenticated'
  images:
    - gcr.io/$PROJECT_ID/$REPO_NAME:latest