steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --cache=true
      - --dockerfile=Dockerfile
    id: build
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy
    args:
      - run
      - deploy
      - $REPO_NAME
      - --image
      - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --region
      - europe-west1
      - '--set-env-vars=ENTUR_BASEURL=$_ENTUR_BASEURL,PERIOD_TICKET_INVITE_KEY=$_PERIOD_TICKET_INVITE_KEY,TICKET_INVITE_KEY=$_TICKET_INVITE_KEY,FLEX_TICKET_INVITE_KEY=$_FLEX_TICKET_INVITE_KEY'
      - --platform
      - managed
      - --allow-unauthenticated
substitutions:
  _ENTUR_BASEURL: 'https://api.staging.entur.io'
  _PERIOD_TICKET_INVITE_KEY: 'period-ticket-staging'
  _TICKET_INVITE_KEY: 'ticket-invite-staging'
  _FLEX_TICKET_INVITE_KEY: 'flex-ticket-invite-staging'
timeout: 1500s
