# docker build -t 'gcr.io/atb-mobility-platform/atb-bff-test:sha' -f 'Dockerfile.test' .
# docker run -e environment=staging gcr.io/atb-mobility-platform/atb-bff-test:sha

FROM node:16.18-alpine3.16 as dependencies
WORKDIR /test
COPY ./test/package.json /test/yarn.lock ./
RUN yarn install


FROM node:16.18-alpine3.16 as build
WORKDIR /test
COPY --from=dependencies /test/node_modules ./node_modules
COPY ./test/src ./src
COPY ./test/.babelrc ./
COPY ./test/package.json ./
COPY ./test/tsconfig.json ./
COPY ./test/webpack.config.js ./
RUN yarn webpack


FROM grafana/k6:latest as run_tests
WORKDIR /test
COPY --from=build --chown=12345 /test/dist ./dist
ENTRYPOINT k6 run ./dist/k6.js