swagger: '2.0'
info:
  title: atb-bff
  description: ATB BFF
  version: 1.0.0
host: atb-bff-jlmnrncfba-ew.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://atb-bff-jlmnrncfba-ew.a.run.app
  path_translation: APPEND_PATH_TO_ADDRESS
paths:
  /bff/v1/departures:
    get:
      summary: Find departures between stop places
      operationId: getBffV1Departures
      parameters:
        - type: string
          name: from
          in: query
          required: true
        - type: string
          name: to
          in: query
          required: true
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
      deprecated: true
  /bff/v1/departures-realtime:
    get:
      summary: Get updated realtime information of all lines and quays passed as data
      operationId: getBffV1Departuresrealtime
      parameters:
        - type: array
          default: []
          items:
            type: string
          collectionFormat: multi
          name: quayIds
          in: query
        - type: string
          format: date
          name: startTime
          in: query
        - type: number
          default: 5
          name: limit
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v1/stops:
    get:
      summary: Find stops matching query
      operationId: getBffV1Stops
      parameters:
        - type: string
          name: query
          in: query
          required: true
        - type: number
          name: lat
          in: query
        - type: number
          name: lon
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
      deprecated: true
  /bff/v1/departures/nearest:
    get:
      summary: >-
        Get departures from stops near coordinates. Deprecated: Use POST
        /v1/departures-from-location instead
      operationId: getBffV1DeparturesNearest
      parameters:
        - type: number
          name: lat
          in: query
          required: true
        - type: number
          name: lon
          in: query
          required: true
        - type: number
          default: 60000
          name: offset
          in: query
        - type: number
          default: 1.3
          name: walkSpeed
          in: query
        - type: boolean
          default: false
          name: includeIrrelevant
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
      deprecated: true
  /bff/v1/geocoder/features:
    get:
      summary: Find features matching query
      operationId: getBffV1GeocoderFeatures
      parameters:
        - type: string
          name: query
          in: query
          required: true
        - type: number
          name: lon
          in: query
        - type: number
          name: lat
          in: query
        - type: string
          name: layers
          in: query
        - type: string
          name: tariff_zone_authorities
          in: query
        - type: number
          name: boundary.rect.min_lat
          in: query
        - type: number
          name: boundary.rect.max_lat
          in: query
        - type: number
          name: boundary.rect.min_lon
          in: query
        - type: number
          name: boundary.rect.max_lon
          in: query
        - type: string
          name: country
          in: query
        - type: string
          name: sources
          in: query
        - type: number
          name: limit
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v1/geocoder/reverse:
    get:
      summary: 'Find addresses, POIs and stop places near the given coordinates'
      operationId: getBffV1GeocoderReverse
      parameters:
        - type: number
          name: lat
          in: query
          required: true
        - type: number
          name: lon
          in: query
          required: true
        - type: string
          name: layers
          in: query
        - type: number
          name: radius
          in: query
        - type: number
          name: limit
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v1/journey/single-trip:
    get:
      summary: Get one specific trip pattern from generated ID
      operationId: getBffV1JourneySingletrip
      parameters:
        - type: string
          name: id
          in: query
          required: true
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v1/journey/trip:
    get:
      summary: Find trip patterns with a simple query
      operationId: getBffV1JourneyTrip
      parameters:
        - type: string
          name: from
          in: query
          required: true
        - type: string
          name: to
          in: query
          required: true
        - type: string
          format: date
          name: when
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
    post:
      summary: Find trip patterns
      operationId: postBffV1JourneyTrip
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Model5'
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  '/bff/v1/stop/{id}':
    get:
      summary: Get details for a StopPlace
      operationId: getBffV1StopId
      parameters:
        - type: string
          name: id
          in: path
          required: true
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v1/stops/nearest:
    get:
      summary: Find stops near coordinates
      operationId: getBffV1StopsNearest
      parameters:
        - type: number
          name: lat
          in: query
          required: true
        - type: number
          name: lon
          in: query
          required: true
        - type: number
          name: distance
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
      deprecated: true
  '/bff/v1/quay/{id}/departures':
    get:
      summary: Get departures from Quay
      operationId: getBffV1QuayIdDepartures
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: string
          format: date
          name: start
          in: query
        - type: number
          name: timeRange
          in: query
        - type: number
          name: limit
          in: query
        - type: boolean
          name: includeNonBoarding
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  '/bff/v1/servicejourney/{id}/departures':
    get:
      summary: Get departures for Service Journey
      operationId: getBffV1ServicejourneyIdDepartures
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: string
          format: date
          name: date
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  '/bff/v1/servicejourney/{id}/polyline':
    get:
      summary: Get departures for Service Journey
      operationId: getBffV1ServicejourneyIdPolyline
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: string
          name: fromQuayId
          in: query
        - type: string
          name: toQuayId
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  '/bff/v1/stop/{id}/departures':
    get:
      summary: >-
        Get departures from StopPlace. Deprecated: Use POST
        /v1/departures-from-location instead
      operationId: getBffV1StopIdDepartures
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: string
          format: date
          name: start
          in: query
        - type: number
          name: timeRange
          in: query
        - type: number
          name: limit
          in: query
        - type: boolean
          name: includeNonBoarding
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
      deprecated: true
  '/bff/v1/stop/{id}/quays':
    get:
      summary: Get all quays that belongs to a StopPlace
      operationId: getBffV1StopIdQuays
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: boolean
          default: false
          name: filterByInUse
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v1/departures-from-location:
    post:
      summary: Get departures from feature location
      operationId: postBffV1Departuresfromlocation
      parameters:
        - type: number
          default: 5
          name: limit
          in: query
        - type: boolean
          default: false
          name: includeNonBoarding
          in: query
        - type: number
          default: 60000
          name: offset
          in: query
        - type: number
          default: 1.3
          name: walkSpeed
          in: query
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Model1'
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
      deprecated: true
  /bff/v1/departures-from-location-paging:
    post:
      summary: Get departures from feature location
      operationId: postBffV1Departuresfromlocationpaging
      parameters:
        - type: number
          default: 5
          name: limit
          in: query
        - type: string
          format: date
          default: '2021-01-27T09:48:19.330Z'
          name: startTime
          in: query
        - type: number
          default: 10
          name: pageSize
          in: query
        - type: number
          default: 0
          name: pageOffset
          in: query
        - type: number
          description: Deprecated
          default: 60000
          name: offset
          in: query
        - type: number
          description: Deprecated
          default: 1.3
          name: walkSpeed
          in: query
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Model1'
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
      deprecated: true
  /bff/v1/departures-grouped:
    post:
      summary: Get departures grouped on lines from feature location
      operationId: postBffV1Departuresgrouped
      parameters:
        - type: number
          default: 5
          name: limitPerLine
          in: query
        - type: string
          format: date
          default: '2021-01-27T09:48:19.354Z'
          name: startTime
          in: query
        - type: number
          default: 3
          name: pageSize
          in: query
        - type: string
          name: cursor
          in: query
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Model4'
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v1/enrollment/group:
    post:
      summary: Enroll in beta groups with invite key
      operationId: postBffV1EnrollmentGroup
      parameters:
        - type: string
          name: inviteKey
          in: query
          required: true
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v2/departures/stops-nearest:
    get:
      summary: Get stops geographically nearest to a set of coordinates
      operationId: getBffV2StopsNearest
      parameters:
        - type: number
          name: latitude
          in: query
          required: true
        - type: number
          name: longitude
          in: query
          required: true
        - type: number
          name: distance
          default: 1000
          in: query
        - type: number
          name: count
          default: 10
          in: query
        - type: string
          name: after
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v2/departures/stop-departures:
    get:
      summary: Get stop with departures for every quay
      operationId: getBffV2StopDepartures
      parameters:
        - type: string
          name: id
          in: query
          required: true
        - type: number
          name: numberOfDepartures
          default: 10
          in: query
        - type: string
          format: date
          default: '2021-01-27T09:48:19.354Z'
          name: startTime
          in: query
        - type: number
          name: timeRange
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v2/departures/quay-departures:
    get:
      summary: Get departures from a quay
      operationId: getBffV2QuayDepartures
      parameters:
        - type: string
          name: id
          in: query
          required: true
        - type: number
          name: numberOfDepartures
          default: 5
          in: query
        - type: string
          format: date
          default: '2021-01-27T09:48:19.330Z'
          name: startTime
          in: query
        - type: number
          name: timeRange
          default: 86400
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v2/departures/realtime:
    get:
      summary: Get updated realtime information for the given quays
      operationId: getBffV2Departuresrealtime
      parameters:
        - type: array
          default: []
          items:
            type: string
          collectionFormat: multi
          name: quayIds
          in: query
        - type: string
          format: date
          name: startTime
          in: query
        - type: number
          default: 5
          name: limit
          in: query
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
  /bff/v2/trips:
    post:
      summary: Get trips between stops
      operationId: postBffV2_0Trips
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/TripsModel'
      tags:
        - bff
      responses:
        default:
          schema:
            type: string
          description: Successful
definitions:
  coordinates:
    type: object
    properties:
      longitude:
        type: number
      latitude:
        type: number
  Model1:
    type: object
    properties:
      layer:
        type: string
      id:
        type: string
      coordinates:
        $ref: '#/definitions/coordinates'
  Model2:
    type: object
    properties:
      layer:
        type: string
        enum:
          - override: true
          - venue
      id:
        type: string
  Model3:
    type: object
    properties:
      stopId:
        type: string
      lineName:
        type: string
      lineId:
        type: string
    required:
      - stopId
      - lineName
      - lineId
  favorites:
    type: array
    items:
      $ref: '#/definitions/Model3'
  Model4:
    type: object
    properties:
      location:
        $ref: '#/definitions/Model2'
        x-alternatives:
          - $ref: '#/x-alt-definitions/location'
          - $ref: '#/x-alt-definitions/Model1'
      favorites:
        $ref: '#/definitions/favorites'
    required:
      - location
  from:
    type: object
    properties:
      place:
        type: string
      name:
        type: string
        default: UNKNOWN
      coordinates:
        $ref: '#/definitions/coordinates'
  modes:
    type: array
    default:
      - foot
      - bus
      - tram
      - rail
      - metro
      - water
      - air
    items:
      type: string
  Model5:
    type: object
    properties:
      from:
        $ref: '#/definitions/from'
      to:
        $ref: '#/definitions/from'
      searchDate:
        type: string
        format: date
      arriveBy:
        type: boolean
        default: false
      minimumTransferTime:
        type: number
        default: 30
      modes:
        $ref: '#/definitions/modes'
      limit:
        type: number
        default: 10
      wheelchairAccessible:
        type: boolean
        default: false
    required:
      - from
      - to
  TripsModel:
    type: object
    properties:
      from:
        $ref: '#/definitions/from'
      to:
        $ref: '#/definitions/from'
      when:
        type: string
        format: date
      arriveBy:
        type: boolean
      cursor:
        type: string
      transferPenalty:
        type: number
      waitReluctance:
        type: number
      walkReluctance:
        type: number
      walkSpeed:
        type: number
    required:
      - from
      - to
      - arriveBy
x-alt-definitions:
  location:
    type: object
    properties:
      layer:
        type: string
        enum:
          - override: true
          - venue
      id:
        type: string
  coordinates:
    type: object
    properties:
      longitude:
        type: number
      latitude:
        type: number
  Model1:
    type: object
    properties:
      layer:
        type: string
        enum:
          - override: true
          - address
      coordinates:
        $ref: '#/x-alt-definitions/coordinates'
