name: Docker Build, Push & Deploy

on:
  release:
    types: [published]
  push:
    branches: ['main']

jobs:
  build:
    uses: atb-as/workflows/.github/workflows/cluster-docker-build-tag-push.yaml@v1
    with:
      application: amp
      image: gcr.io/atb-mobility-platform/atb-bff
      instance_id: bff
    secrets:
      github_pat: ${{ secrets.GH_PAT }}
