name: Test
on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'

jobs:
  lint:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
