name: Test
on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'

jobs:
  lint:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
