name: Test
on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
